# Generated by Django 3.2 on 2022-10-11 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('educitons', models.TextField(blank=True, max_length=300, null=True)),
                ('exprince', models.TextField(blank=True, max_length=150, null=True)),
                ('number', models.CharField(max_length=12)),
                ('city', models.CharField(choices=[('Karthum', 'Karthum'), ('omdrman', 'omdrman'), ('bahri', 'bahri'), ('sharq alnel', 'sharq alnel')], max_length=12)),
                ('tech', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='techer')),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
