# Generated by Django 3.2 on 2022-10-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221011_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='oders',
        ),
        migrations.AddField(
            model_name='oder',
            name='techer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.oder'),
        ),
    ]
