# Generated by Django 3.2 on 2022-10-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.IntegerField()),
                ('company_country', models.CharField(max_length=15)),
                ('company_city', models.CharField(max_length=15)),
                ('company_email', models.IntegerField()),
            ],
        ),
    ]
